version: "3.4"
services:
  gaben:    
    container_name: gaben-bot
    restart: unless-stopped
    env_file:
      - .env
    build:      
      context: .
      dockerfile: ./Dockerfile
    depends_on: [ esdb ]        
  esdb:
    container_name: gaben-esdb
    restart: unless-stopped
    image: eventstore/eventstore:24.2
    user: "${UID}:${GID}"
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - "./data/esdb:/var/lib/eventstore"
      - "./logs/esdb:/var/log/eventstore"

